[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "shotgun-stochastic-search"
version = "0.1.0"
description = "Python implementation of Shotgun Stochastic Search for 'Large p' Regression"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "scikit-learn",
    "tqdm",
    "matplotlib",
    "seaborn",
    "joblib"
]

[tool.setuptools]
packages = ["shotgun_stochastic_search"]

[project.optional-dependencies]
dev = [
    "pytest",
]
